[tasks.install-lock]
run = "touch mise.lock && mise install"

[tools.node]
version = "latest"

[tools.bun]
version = "latest"

[tools.ruby]
version = "3.4.4"

[tools.java]
version = "temurin-24"

[tools]
"gem:bundler" = "latest"
"gem:cocoapods" = "latest"
"firebase" = "latest"

# ruby 의존성
[tasks.ruby_dependencies_install]
run = "brew install openssl@3 readline libyaml gmp autoconf"

# mise에 watchman이 없으므로
[tasks.install_watchman]
run = "brew install watchman"

[tasks.pod_install]
run = "cd ios && pod install --repo-update && cd .."

[tasks.xcode]
run = "xed ios"

[tasks.ios_cache_clear]
run = """
rm -rf node_modules
npm cache clean --force
npm install
watchman watch-del-all
rm -fr $TMPDIR/haste-map-*
rm -rf $TMPDIR/metro-cache
npx expo prebuild --clear
"""

[env]
NODE_COMPILE_CACHE = { value = "~/.cache/nodejs-compile-cache", tools = true }
