defmodule Deopjib.Repo.Migrations.UpdateNameOrAddPayerBancAccountField do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:payer) do
      add :banc_account, :text, default: ""
    end

    rename table(:pay_item), :price, to: :amount
  end

  def down do
    rename table(:pay_item), :amount, to: :price

    alter table(:payer) do
      remove :banc_account
    end
  end
end
