defmodule Deopjib.Repo.Migrations.ChangePayerItemSettlerIdsToSettlerId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:pay_item), :settled_ids, to: :settled_id

    drop constraint(:pay_item, "pay_item_settled_ids_fkey")

    alter table(:pay_item) do
      modify :price, :bigint, default: 0

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      modify :settled_id,
             references(:payer,
               column: :id,
               name: "pay_item_settled_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end
  end

  def down do
    drop constraint(:pay_item, "pay_item_settled_id_fkey")

    alter table(:pay_item) do
      modify :settled_ids,
             references(:payer,
               column: :id,
               name: "pay_item_settled_ids_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )

      remove :updated_at
      modify :price, :bigint, default: nil
    end

    rename table(:pay_item), :settled_id, to: :settled_ids
  end
end
