defmodule Deopjib.Repo.Migrations.AddPayItem do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pay_item, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :price, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :room_id,
          references(:rooms,
            column: :id,
            name: "pay_item_room_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :settled_ids,
          references(:payer,
            column: :id,
            name: "pay_item_settled_ids_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:pay_item, "pay_item_room_id_fkey")

    drop constraint(:pay_item, "pay_item_settled_ids_fkey")

    drop table(:pay_item)
  end
end
