defmodule Deopjib.Repo.Migrations.RoomDeleteOnPayerDelteToo do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:payer, "payer_room_id_fkey")

    alter table(:payer) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "payer_room_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:payer, "payer_room_id_fkey")

    alter table(:payer) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "payer_room_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
