defmodule Deopjib.Repo.Migrations.AddPayItemExcludedPayer do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pay_item_excluded_payers, primary_key: false) do
      add(
        :pay_item_id,
        references(:pay_item,
          column: :id,
          name: "pay_item_excluded_payers_pay_item_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        primary_key: true,
        null: false
      )

      add(
        :payer_id,
        references(:payer,
          column: :id,
          name: "pay_item_excluded_payers_payer_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        primary_key: true,
        null: false
      )
    end
  end

  def down do
    drop(constraint(:pay_item_excluded_payers, "pay_item_excluded_payers_pay_item_id_fkey"))

    drop(constraint(:pay_item_excluded_payers, "pay_item_excluded_payers_payer_id_fkey"))

    drop(table(:pay_item_excluded_payers))
  end
end
