[tools.sops]
version = "latest"

[tools.age]
version = "latest"

[tools.just]
version = "latest"

[tools.elixir]
version = "latest"

[tools.elixir-ls]
version = "latest"

# # nix flake의 패키지 사용
# [tools]
# age = "nix:age@."
# sops = "nix:sops@."
# ssh-to-age = "nix:ssh-to-age@."

[env]
_.file = [
  ".env-local.json",
]
