[tools.erlang]
version = "27.3.4"

[tools.elixir]
version = "1.18.4-otp-27"

[tools.just]
version = "latest"

[tools.age]
version = "latest"

[tools.elixir-ls]
version = "latest"

[tools.flyctl]
version = "latest"
