[tools.erlang]
version = "28"

[tools.elixir]
version = "1.19.0-rc.0-otp-28"

[tools.just]
version = "latest"

[tools.age]
version = "latest"

[tools.elixir-ls]
version = "latest"

[tools.flyctl]
version = "latest"
