
[tools.age]
version = "latest"

[tools.sops]
version = "latest"

[tools.just]
version = "latest"

[tools.elixir]
version = "latest"

[tools.elixir-ls]
version = "latest"


[env]
_.file = [
  ".env-local.json",
  ".secreat-env.json"
]

PROJECT_NAME = { value = "deopjib", tools = true }
PROJECT_ENV = { value = "dev", tools = true }
PROJECT_ROOT = { value = "{{config_root}}", tools = true }
