import fs from 'fs';
import path from 'path';


// ../src/icons의 파일들의 이름을 기준으로 iconNames 타입 만들기
const iconNames = fs.readdirSync(path.join(process.cwd(), 'src/icons')).map(file => file.replace('.svg', ''));


const OUTPUT_FILE = path.join(process.cwd(), 'src/components/ui/Icon/IconMap.gen.tsx');

function generateMagicalIconMap() {
  const toPascalCase = (str: string) =>
    str.split('_').map(part =>
      part.charAt(0).toUpperCase() + part.slice(1)
    ).join('');

  // React 컴포넌트 import
  const componentImports = iconNames
    .map(name => {
      const pascalName = toPascalCase(name);
      return `import ${pascalName}Component from "@/icons/${name}.svg";`;
    })
    .join('\n');

  // 파일 URL import
  const fileImports = iconNames
    .map(name => {
      const pascalName = toPascalCase(name);
      return `import ${pascalName}File from "@/icons/${name}.svg?file";`;
    })
    .join('\n');

  // 컴포넌트 맵
  const componentMapEntries = iconNames
    .map(name => {
      const pascalName = toPascalCase(name);
      return `  "${name}": ${pascalName}Component,`;
    })
    .join('\n');

  // 파일 URL 맵
  const fileMapEntries = iconNames
    .map(name => {
      const pascalName = toPascalCase(name);
      return `  "${name}": ${pascalName}File,`;
    })
    .join('\n');

  const content = `// 자동 생성된 파일 - 수정하지 마세요
// Generated by generate-magical-icons.ts

import { type SVGProps } from "react";

// React 컴포넌트로 import
${componentImports}

// 파일 URL로 import
${fileImports}

export const iconComponents: Record<IconName, React.ComponentType<SVGProps<SVGSVGElement>>> = {
${componentMapEntries}
};

export const iconFiles: Record<IconName, string> = {
${fileMapEntries}
};

export function getIconComponent(name: IconName) {
  return iconComponents[name];
}

export function getIconFile(name: IconName) {
  return iconFiles[name];
}

// 모든 아이콘 이름 배열 (개발 도구용)
export const availableIcons = [${iconNames.map(name => `"${name}"`).join(', ')}] as const;
export type IconName = typeof availableIcons[number];
`;

  fs.writeFileSync(OUTPUT_FILE, content);
  console.log(`✅ Icon map generated with ${iconNames.length} icons (components + files)!`);
}

generateMagicalIconMap();
