/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/room/create`; params?: Router.UnknownInputParams; } | { pathname: `/room/[roomId]/[userId]`, params: Router.UnknownInputParams & { roomId: string | number;userId: string | number; } } | { pathname: `/room/[roomId]/payment`, params: Router.UnknownInputParams & { roomId: string | number; } } | { pathname: `/room/[roomId]/receipt`, params: Router.UnknownInputParams & { roomId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/room/create`; params?: Router.UnknownOutputParams; } | { pathname: `/room/[roomId]/[userId]`, params: Router.UnknownOutputParams & { roomId: string;userId: string; } } | { pathname: `/room/[roomId]/payment`, params: Router.UnknownOutputParams & { roomId: string; } } | { pathname: `/room/[roomId]/receipt`, params: Router.UnknownOutputParams & { roomId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/auth${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/room/create${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/room/create`; params?: Router.UnknownInputParams; } | `/room/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/room/${Router.SingleRoutePart<T>}/payment${`?${string}` | `#${string}` | ''}` | `/room/${Router.SingleRoutePart<T>}/receipt${`?${string}` | `#${string}` | ''}` | { pathname: `/room/[roomId]/[userId]`, params: Router.UnknownInputParams & { roomId: string | number;userId: string | number; } } | { pathname: `/room/[roomId]/payment`, params: Router.UnknownInputParams & { roomId: string | number; } } | { pathname: `/room/[roomId]/receipt`, params: Router.UnknownInputParams & { roomId: string | number; } };
    }
  }
}
