// 자동 생성된 파일 - 수정하지 마세요
// Generated by generate-magical-icons.ts
// gen version 2025-09-09T01:38:18.464Z

import { type SVGProps } from "react";

// React 컴포넌트로 import
import CreateComponent from "@shared/ui/Icon/svgs/create.svg";
import PenComponent from "@shared/ui/Icon/svgs/pen.svg";
import ArrowLeftComponent from "@shared/ui/Icon/svgs/arrow_left.svg";
import ArrowUpComponent from "@shared/ui/Icon/svgs/arrow_up.svg";
import Share1Component from "@shared/ui/Icon/svgs/share1.svg";
import ArrowRightComponent from "@shared/ui/Icon/svgs/arrow_right.svg";
import PlusComponent from "@shared/ui/Icon/svgs/plus.svg";
import CheckComponent from "@shared/ui/Icon/svgs/check.svg";
import ArrowDownComponent from "@shared/ui/Icon/svgs/arrow_down.svg";
import TrashComponent from "@shared/ui/Icon/svgs/trash.svg";
import CalendarComponent from "@shared/ui/Icon/svgs/calendar.svg";
import CrossComponent from "@shared/ui/Icon/svgs/cross.svg";
import MinusComponent from "@shared/ui/Icon/svgs/minus.svg";

// 파일 URL로 import
import CreateFile from "@shared/ui/Icon/svgs/create.svg?file";
import PenFile from "@shared/ui/Icon/svgs/pen.svg?file";
import ArrowLeftFile from "@shared/ui/Icon/svgs/arrow_left.svg?file";
import ArrowUpFile from "@shared/ui/Icon/svgs/arrow_up.svg?file";
import Share1File from "@shared/ui/Icon/svgs/share1.svg?file";
import ArrowRightFile from "@shared/ui/Icon/svgs/arrow_right.svg?file";
import PlusFile from "@shared/ui/Icon/svgs/plus.svg?file";
import CheckFile from "@shared/ui/Icon/svgs/check.svg?file";
import ArrowDownFile from "@shared/ui/Icon/svgs/arrow_down.svg?file";
import TrashFile from "@shared/ui/Icon/svgs/trash.svg?file";
import CalendarFile from "@shared/ui/Icon/svgs/calendar.svg?file";
import CrossFile from "@shared/ui/Icon/svgs/cross.svg?file";
import MinusFile from "@shared/ui/Icon/svgs/minus.svg?file";

export const iconComponents = {
  "create": CreateComponent,
  "pen": PenComponent,
  "arrow_left": ArrowLeftComponent,
  "arrow_up": ArrowUpComponent,
  "share1": Share1Component,
  "arrow_right": ArrowRightComponent,
  "plus": PlusComponent,
  "check": CheckComponent,
  "arrow_down": ArrowDownComponent,
  "trash": TrashComponent,
  "calendar": CalendarComponent,
  "cross": CrossComponent,
  "minus": MinusComponent,
} as const satisfies Record<IconName, React.FC<SVGProps<SVGSVGElement>>>

export const iconFiles: Record<IconName, string> = {
  "create": CreateFile,
  "pen": PenFile,
  "arrow_left": ArrowLeftFile,
  "arrow_up": ArrowUpFile,
  "share1": Share1File,
  "arrow_right": ArrowRightFile,
  "plus": PlusFile,
  "check": CheckFile,
  "arrow_down": ArrowDownFile,
  "trash": TrashFile,
  "calendar": CalendarFile,
  "cross": CrossFile,
  "minus": MinusFile,
};

export function getIconComponent(name: IconName) {
  return iconComponents[name];
}

export function getIconFile(name: IconName) {
  return iconFiles[name];
}

// 모든 아이콘 이름 배열 (개발 도구용)
export const availableIcons = ["create", "pen", "arrow_left", "arrow_up", "share1", "arrow_right", "plus", "check", "arrow_down", "trash", "calendar", "cross", "minus"] as const;
export type IconName = typeof availableIcons[number];
