// 자동 생성된 파일 - 수정하지 마세요
// Generated by generate-magical-icons.ts

import { type SVGProps } from "react";

// React 컴포넌트로 import
import CreateComponent from "@/icons/create.svg";
import PenComponent from "@/icons/pen.svg";
import ArrowLeftComponent from "@/icons/arrow_left.svg";
import ArrowUpComponent from "@/icons/arrow_up.svg";
import Share1Component from "@/icons/share1.svg";
import ArrowRightComponent from "@/icons/arrow_right.svg";
import PlusComponent from "@/icons/plus.svg";
import CheckComponent from "@/icons/check.svg";
import ArrowDownComponent from "@/icons/arrow_down.svg";
import TrashComponent from "@/icons/trash.svg";
import CalendarComponent from "@/icons/calendar.svg";
import CrossComponent from "@/icons/cross.svg";
import MinusComponent from "@/icons/minus.svg";

// 파일 URL로 import
import CreateFile from "@/icons/create.svg?file";
import PenFile from "@/icons/pen.svg?file";
import ArrowLeftFile from "@/icons/arrow_left.svg?file";
import ArrowUpFile from "@/icons/arrow_up.svg?file";
import Share1File from "@/icons/share1.svg?file";
import ArrowRightFile from "@/icons/arrow_right.svg?file";
import PlusFile from "@/icons/plus.svg?file";
import CheckFile from "@/icons/check.svg?file";
import ArrowDownFile from "@/icons/arrow_down.svg?file";
import TrashFile from "@/icons/trash.svg?file";
import CalendarFile from "@/icons/calendar.svg?file";
import CrossFile from "@/icons/cross.svg?file";
import MinusFile from "@/icons/minus.svg?file";

export const iconComponents: Record<IconName, React.ComponentType<SVGProps<SVGSVGElement>>> = {
  "create": CreateComponent,
  "pen": PenComponent,
  "arrow_left": ArrowLeftComponent,
  "arrow_up": ArrowUpComponent,
  "share1": Share1Component,
  "arrow_right": ArrowRightComponent,
  "plus": PlusComponent,
  "check": CheckComponent,
  "arrow_down": ArrowDownComponent,
  "trash": TrashComponent,
  "calendar": CalendarComponent,
  "cross": CrossComponent,
  "minus": MinusComponent,
};

export const iconFiles: Record<IconName, string> = {
  "create": CreateFile,
  "pen": PenFile,
  "arrow_left": ArrowLeftFile,
  "arrow_up": ArrowUpFile,
  "share1": Share1File,
  "arrow_right": ArrowRightFile,
  "plus": PlusFile,
  "check": CheckFile,
  "arrow_down": ArrowDownFile,
  "trash": TrashFile,
  "calendar": CalendarFile,
  "cross": CrossFile,
  "minus": MinusFile,
};

export function getIconComponent(name: IconName) {
  return iconComponents[name];
}

export function getIconFile(name: IconName) {
  return iconFiles[name];
}

// 모든 아이콘 이름 배열 (개발 도구용)
export const iconNames = ["create", "pen", "arrow_left", "arrow_up", "share1", "arrow_right", "plus", "check", "arrow_down", "trash", "calendar", "cross", "minus"] as const;
export type IconName = typeof iconNames[number];
