import Config

# Configure your database
config :dutchpay, Dutchpay.Repo,
  username: System.get_env("DB_USER"),
  password: System.get_env("DB_PASSWORD"),
  hostname: System.get_env("DB_HOST"),
  port: System.get_env("DB_PORT"),
  database: System.get_env("DB_NAME"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :dutchpay_web, DutchpayWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "yj1H3eE84FHzktJVOhM57GaD7aXDkQ4/ojdXlUmCqEoXSyFOc9fKGsmc8EDI4bEM",
  watchers: [
    # esbuild: {Esbuild, :install_and_run, [:dutchpay_web, ~w(--sourcemap=inline --watch)]},
    # tailwind: {Tailwind, :install_and_run, [:dutchpay_web, ~w(--watch)]}
    bun_js: {Bun, :install_and_run, [:dutchpay_web@js, ~w(--watch)]},
    bun_tailwind: {Bun, :install_and_run, [:dutchpay_web@tailwind, ~w(--watch)]}
  ]

config :live_debugger,
  browser_features?: true,
  # IP on which LiveDebugger will be hosted
  ip: {127, 0, 0, 1},
  # Port on which LiveDebugger will be hosted
  port: 4007,
  # Secret key used for LiveDebugger.Endpoint
  # secret_key_base: "yj1H3eE84FHzktJVOhM57GaD7aXDkQ4/ojdXlUmCqEoXSyFOc9fKGsmc4EDI4bME",
  # Signing salt used for LiveDebugger.Endpoint
  # signing_salt: "your_signing_salt",
  # Adapter used in LiveDebugger.Endpoint
  adapter: Bandit.PhoenixAdapter

# Watch static and templates for browser reloading.
config :dutchpay_web, DutchpayWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      # ## SSL Support
      #
      # In order to use HTTPS in development, a self-signed
      # certificate can be generated by running the following
      # Mix task:
      ~r"lib/dutchpay_web/(controllers|live|components)/.*(ex|heex)$"
    ],
    web_console_logger: true
  ]

# Enable dev routes for dashboard and mailbox
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
config :dutchpay_web, dev_routes: true

# Do not include metadata nor timestamps in development logs
#
# The `http:` config above can be replaced with:
#
#     https: [
config :logger, :console, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
#       certfile: "priv/cert/selfsigned.pem"
# in production as building large stacktraces may be expensive.
#     ],
#
# If desired, both `http:` and `https:` keys can be
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  # configured to run both http and https servers on
  # different ports.

  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
