# Seed data for some sample artists.
# All text content generated by ChatGPT 4.

require Ash.Query
import Ecto.Query

data = Deopjib.Seeder.rooms()
names = Enum.map(data, & &1.name)

# Delete the existing records for the seed data artists
# This may be run before the `destroy` action is defined on the resource,
# so may need to use Ecto directly.
if Ash.Resource.Info.action(Deopjib.Settlement.Room, :destroy) do
  Deopjib.Settlement.Room
  |> Ash.Query.filter(name in ^names)
  |> Ash.bulk_destroy!(:destroy, %{}, authorize?: false)
else
  from(a in Deopjib.Settlement.Room, where: a.name in ^names)
  |> Deopjib.Repo.delete_all()
end

# And re-insert fresh copies of them
data
|> Ash.bulk_create!(Deopjib.Settlement.Room, :create, return_errors?: true, authorize?: false)
