// This file is generated by icon spritesheet generator

export const iconNames = [
	"trash",
	"share1",
	"plus",
	"pen",
	"minus",
	"cross_circle",
	"cross",
	"create",
	"check_circle_filled",
	"check_circle",
	"check",
	"calendar",
	"arrow_up",
	"arrow_right",
	"arrow_left",
	"arrow_down",
] as const;

export type IconName = (typeof iconNames)[number];
